name: Run ESLint & Prettier

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npx eslint .
      - run: npx prettier --check .
